### ISSUE TITLE
Transformation between opf geographic coordinates and nerfstudio coordinates

### ISSUE THREAD

**Issue by Wjppppp** [Pix4D/pyopf#13]
Hi,

thank you so much for providing opf conversion tools! This is very helpful.

I used `opf2nerf project.opf --out-dir out_dir/ --nerfstudio` to convert opf folder to a folder ready-for-use in nerfstudio.

Then I trained the model in nerfstudio, exported the outputs as point clouds with the arguement `--save-world-frame`. However, I found the exported point cloud's coordinates can not match neither the geographic coordinates nor coordinates in colmap/points3D.txt. I struggled a lot to find the correct transformation.

Then I dive into `opf2nerf/converter.py`, I found the `scale`, `avg_pos` are not written out anywhere. 

https://github.com/Pix4D/pyopf/blob/ec60ebe62fd656a8e71c528bc234d9a1c374d7a0/src/opf_tools/opf2nerf/converter.py#L173

But these two variables are actually needed to convert the point clouds derived out of nerfstudio into geographic coordinates through an inverse transformation like:

```
geo_position = (nerf_position * scale) + avg_pos
```

please let me know if I was wrong.

Could you please also improve the tool, enabling to explicitly write out the `scale` and `avg_pos` to some place when using `opf2nerf --nerfstudio`? It would be nice to mention how to correctly use `--cam-aabb-size` as well.

Thank you!

**Comment by pani-vishal** [comment]
Hi there,

The `--cam-aabb-size` is used to rescale the camera positions so that they are in a 8x8x8 cube. This was done to match the original NeRF experiments on the synthetic datasets which places the cameras on a 4m radius circle. Since the original NeRF implementation models foreground within a fixed length box (please refer [here](https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md#:~:text=For%20natural%20scenes,for%20an%20example.)), this ensured compatibility with previous NeRF implementations that we were targeting before nerfstudio. 

It seems that nerfstudio doesn't require it anymore.

However, the transformation to get back the geographic coordinates looks correct! To maintain back-compatibility we are working on writing out the `scale` and `avg_pos` to help you get back the geographic coordinates :)

**Comment by krahenbuhl** [comment]
https://github.com/Pix4D/pyopf/pull/14 should hopefully help with your issue @Wjppppp
